[package]

authors = [
    "Michael Aaron Murphy <mmstickman@gmail.com>",
    "Jeremy Soller <jackpot51@gmail.com>",
    "Skyler Berg <skylertheberg@gmail.com>",
    "stratact <stratact1@gmail.com>",
    "AdminXVII <dev.xlheureux@gmail.com>",
    "Hunter Goldstein <hunter.d.goldstein@gmail.com>",
    "jD91mZM2 <me@krake.one>",
    "Agustin Chiappe Berrini <jnieve@gmail.com>",
    "Sag0Sag0 <Sag0Sag0@users.noreply.github.com>",
]
build = "build.rs"
description = "The Ion Shell"
license-file = "LICENSE"
name = "ion-shell"
readme = "README.md"
repository = "https://gitlab.redox-os.org/redox-os/ion"
version = "1.0.0-alpha"
edition = "2018"

[workspace]
members = [
    "members/braces", "members/builtins", "members/lexers", "members/sys",
    "members/ranges", "members/scopes-rs"
]

[dev-dependencies]
criterion = "0.2"
serial_test = "*"
serial_test_derive = "*"

[[bench]]
name = "terminator"
harness = false

[[bench]]
name = "statement"
harness = false

[[bench]]
name = "builtins"
harness = false

[[bin]]
name = "ion"
path = "src/main.rs"

[build-dependencies]
ansi_term = "0.11"
version_check = "0.1.3"

[dependencies]
calculate = { git = "https://gitlab.redox-os.org/redox-os/calc" }
err-derive = "0.1"
glob = "0.3"
itoa = "0.4"
liner = { git = "https://gitlab.redox-os.org/redox-os/liner" }
rand = "0.6.1"
regex = "1.0"
small = { git = "https://gitlab.redox-os.org/redox-os/small", features = ["std"] }
smallvec = "0.6"
unicode-segmentation = "1.2"
xdg = "2.2.0"
ion_braces = { path = "members/braces" }
ion_builtins = { path = "members/builtins" }
ion_lexers = { path = "members/lexers" }
ion_sys = { path = "members/sys" }
ion-ranges = { path = "members/ranges" }
scopes = { path = "members/scopes-rs" }
hashbrown = "0.1.2"
itertools = "0.8"
lexical = "2.0"
object-pool = "0.3.1"
auto_enums = "0.5.5"

[lib]
path = "src/lib/lib.rs"

[profile.release]
lto = true
panic = "abort"
