[package]
authors = [
    "Michael Aaron Murphy <mmstickman@gmail.com>",
    "Hunter Goldstein <hunter.d.goldstein@gmail.com>",
    "Skyler Berg <skylertheberg@gmail.com>",
    "Jeremy Soller <jackpot51@gmail.com>",
    "Michael Gattozzi <mgattozzi@gmail.com>",
    "≈Åukasz Niemier <lukasz@niemier.pl>",
]
build = "build.rs"
description = "The Ion Shell"
license-file = "LICENSE"
name = "ion-shell"
readme = "README.md"
repository = "https://github.com/redox-os/ion"
version = "1.0.0-alpha"

[[bin]]
name = "ion"
path = "src/main.rs"

[build-dependencies]
ansi_term = "0.10"
version_check = "0.1.3"

[dependencies]
bitflags = "1.0"
calculate = "0.5"
failure = "0.1"
failure_derive = "0.1"
fnv = "1.0"
glob = "0.2"
itoa = "0.4"
lazy_static = "1.0"
liner = "0.4"
permutate = "0.3"
rand = "0.4"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
smallstring = "0.1"
smallvec = "0.6"
toml = "0.4"
unicode-segmentation = "1.2"
xdg = { git = "https://github.com/whitequark/rust-xdg" }

[lib]
path = "src/lib/lib.rs"

[profile.release]
lto = true
panic = "abort"
[target."cfg(all(unix, not(target_os = \"redox\")))".dependencies]
libc = "0.2"
libloading = "0.5"
users = "0.6"
[target."cfg(target_os = \"redox\")".dependencies]
redox_syscall = "0.1"
