[package]
name = "ion-shell"
description = "The Ion Shell"
repository = "https://github.com/redox-os/ion"
version = "1.0.0"
license-file = "LICENSE"
readme = "README.md"
authors = [
  "Michael Aaron Murphy <mmstickman@gmail.com>",
  "Skyler Berg <skylertheberg@gmail.com>",
  "Jeremy Soller <jackpot51@gmail.com>",
  "Michael Gattozzi <mgattozzi@gmail.com>",
  "≈Åukasz Niemier <lukasz@niemier.pl>",
]

[[bin]]
name = "ion"

[dependencies]
glob = "0.2"
liner = "0.1"
peg-syntax-ext = "0.4"
permutate = "0.2"

[target.'cfg(all(unix, not(target_os = "redox")))'.dependencies]
users = "0.5.1"
