[package]
authors = [
    "Michael Aaron Murphy <mmstickman@gmail.com>",
    "Hunter Goldstein <hunter.d.goldstein@gmail.com>",
    "Skyler Berg <skylertheberg@gmail.com>",
    "Jeremy Soller <jackpot51@gmail.com>",
    "Michael Gattozzi <mgattozzi@gmail.com>",
    "≈Åukasz Niemier <lukasz@niemier.pl>",
]
build = "build.rs"
description = "The Ion Shell"
license-file = "LICENSE"
name = "ion-shell"
readme = "README.md"
repository = "https://github.com/redox-os/ion"
version = "1.0.5"

[[bin]]
name = "ion"
path = "src/main.rs"

[build-dependencies]
ansi_term = "0.9"
version_check = "0.1.3"

[dependencies]
bitflags = "0.9.1"
calculate = "0.5"
fnv = "1.0"
glob = "0.2"
lazy_static = "0.2"
liner = "0.4"
permutate = "0.3"
regex = "0.2"
smallstring = "0.1"
smallvec = "0.4"
unicode-segmentation = "1.2"

[dependencies.app_dirs]
git = "https://github.com/redox-os/app-dirs-rs.git"

[profile.release]
panic = "abort"

[target."cfg(all(unix, not(target_os = \"redox\")))".dependencies]
errno = "0.2.3"
libc = "0.2"
libloading = "0.4"
users = "0.5.1"

[target."cfg(target_os = \"redox\")".dependencies]
redox_syscall = "0.1"
