[package]
name = "ion-shell"
description = "The Ion Shell"
repository = "https://github.com/redox-os/ion"
version = "0.1.2"
license-file = "LICENSE"
readme = "README.md"
authors = [
  "Skyler Berg <skylertheberg@gmail.com>",
  "Jeremy Soller <jackpot51@gmail.com>",
  "Michael Gattozzi <mgattozzi@gmail.com>",
  "≈Åukasz Niemier <lukasz@niemier.pl>",
]

[dependencies]
peg = "*"
glob = "*"
regex = "0.1"
