[package]
name = "ion-shell"
description = "The Ion Shell"
repository = "https://github.com/redox-os/ion"
version = "1.0.3"
license-file = "LICENSE"
readme = "README.md"
authors = [
  "Michael Aaron Murphy <mmstickman@gmail.com>",
  "Skyler Berg <skylertheberg@gmail.com>",
  "Jeremy Soller <jackpot51@gmail.com>",
  "Michael Gattozzi <mgattozzi@gmail.com>",
  "≈Åukasz Niemier <lukasz@niemier.pl>",
]
build = "build.rs"

[[bin]]
name = "ion"

[dependencies]
bitflags = "0.9.1"
fnv = "1.0"
glob = "0.2"
liner = "0.2"
permutate = "0.3"
unicode-segmentation = "1.2"
smallvec = "0.4"
smallstring = "0.1"

[target.'cfg(not(target_os = "redox"))'.dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-signal = "0.1"

[target.'cfg(all(unix, not(target_os = "redox")))'.dependencies]
users = "0.5.1"

[build-dependencies]
peg = "0.5"
ansi_term = "0.9"
version_check = "0.1"

[profile.release]
debug = true
# rustflags = [ "-C", "target-cpu=native"]
lto = true
panic = "abort"
